export { Home } from './home'
export { Awards } from './awards'
export { News } from './news'
export { Library } from './library'
export { Activities } from './activities'
export { Contact } from './contact'
export { Admin } from './admin'
